### ISSUE TITLE
How to use your reo

### ISSUE THREAD

**Issue by ghost** [ShreshthSaxena/Faster-RCNN#1]
Hi @ShreshthSaxena .. i Am glad that to found your repo.Can you please elaborate little hoe to use your repo without googlcolab

**Comment by ShreshthSaxena** [comment]
hey, you can install Jupyter Notebook and run the ipynb file on your local machine.
hope that helps !

**Comment by ghost** [comment]
Hi @ShreshthSaxena  this is the first error i m getting
![error](https://user-images.githubusercontent.com/58855073/80008910-f621aa00-84e5-11ea-8aae-74df2544b6e1.png)

**Comment by ShreshthSaxena** [comment]
Hi, I please take a look at jupyter/jupyter_client#479.
